import 'package:flutter/material.dart';

enum UiAuditCategory {
  typography(Icons.text_fields),
  actions(Icons.smart_button_outlined),
  fields(Icons.edit_note),
  selection(Icons.toggle_on_outlined),
  surfaces(Icons.dashboard_customize_outlined),
  overlays(Icons.layers_outlined),
  navigation(Icons.navigation_outlined),
  feedback(Icons.notifications_none),
  spacing(Icons.space_bar),
  color(Icons.palette_outlined),
  icons(Icons.auto_awesome_outlined),
  motion(Icons.animation);

  const UiAuditCategory(this.icon);
  final IconData icon;
}

enum UiAuditKind { existing, candidate }

enum UiAuditDecision { review, keep, replace, exception }

@immutable
class UiAuditItem {
  const UiAuditItem({
    required this.id,
    required this.category,
    required this.kind,
    required this.decision,
    required this.name,
    required this.origins,
    required this.states,
    required this.differences,
    required this.rationale,
    required this.risks,
    required this.options,
    required this.recommendation,
  });

  final String id;
  final UiAuditCategory category;
  final UiAuditKind kind;
  final UiAuditDecision decision;
  final String name;
  final List<String> origins;
  final List<String> states;
  final String differences;
  final String rationale;
  final String risks;
  final List<String> options;
  final String recommendation;
}

/// A checked-in snapshot of the UI audit. It is deliberately descriptive:
/// the gallery must not silently turn today's implementation into tomorrow's
/// design system before each family has been reviewed in the sandbox.
const uiAuditCatalog = <UiAuditItem>[
  UiAuditItem(
    id: 'type-page-title-local',
    category: UiAuditCategory.typography,
    kind: UiAuditKind.existing,
    decision: UiAuditDecision.review,
    name: 'Page titles — local recipes',
    origins: [
      'area_detail_screen.dart',
      'settings_screen.dart',
      'stats_screen.dart',
      'quick_settings_screen.dart',
    ],
    states: ['single line', 'wrapped', 'compact viewport'],
    differences: 'Page-level headings use several sizes, weights and top/bottom gaps; some use the star-title font and others the body font.',
    rationale: 'Some screens are immersive while others are utility pages, but the hierarchy is not named in code.',
    risks: 'The same hierarchy level can look unrelated; long translations may wrap into spacing chosen for one line.',
    options: [
      'Keep per-screen recipes',
      'Create one page-title role',
      'Define immersive and utility title roles',
    ],
    recommendation: 'Define two explicit roles: immersive page title and utility page title.',
  ),
  UiAuditItem(
    id: 'type-section-title-local',
    category: UiAuditCategory.typography,
    kind: UiAuditKind.existing,
    decision: UiAuditDecision.replace,
    name: 'Section headings — repeated local styles',
    origins: [
      'area_section_header.dart',
      'area_filter_sheet.dart',
      'kind_filter_sheet.dart',
      'settings_screen.dart',
    ],
    states: ['with body copy', 'standalone', 'inside sheet'],
    differences: 'Section labels range from small uppercase captions to 30 px display headings without a shared semantic API.',
    rationale: 'Different density is sometimes appropriate, but visually equivalent labels are rebuilt locally.',
    risks: 'Hierarchy and vertical rhythm change between screens; maintenance requires editing many call sites.',
    options: [
      'Keep all variants',
      'One section title',
      'Large section heading plus compact section label',
    ],
    recommendation:
        'Keep two semantic levels and document their allowed contexts.',
  ),
  UiAuditItem(
    id: 'type-scale-candidate',
    category: UiAuditCategory.typography,
    kind: UiAuditKind.candidate,
    decision: UiAuditDecision.review,
    name: 'Candidate semantic type scale',
    origins: ['app_theme.dart', 'app_fonts.dart'],
    states: ['normal', 'muted', 'danger', 'long text'],
    differences: 'Replaces raw font sizes with named page, section, body, label and micro-label roles.',
    rationale: 'The audit found 316 explicit font-size declarations spanning more than thirty numeric values.',
    risks: 'A scale that is too small would flatten the expressive screens.',
    options: ['Five roles', 'Five roles plus immersive display roles'],
    recommendation:
        'Use a compact semantic scale plus opt-in immersive display roles.',
  ),
  UiAuditItem(
    id: 'action-material-buttons',
    category: UiAuditCategory.actions,
    kind: UiAuditKind.existing,
    decision: UiAuditDecision.review,
    name: 'Material button family',
    origins: [
      'app_theme.dart',
      'settings_screen.dart',
      'moodboard_screen.dart',
    ],
    states: ['enabled', 'pressed', 'disabled', 'focused'],
    differences: 'Elevated, outlined and text buttons inherit a shared theme, but many call sites override color, padding or size.',
    rationale: 'Material buttons cover ordinary page and dialog actions well.',
    risks: 'Local overrides make identical verbs appear to have different importance.',
    options: ['Theme only', 'Named wrappers', 'Allow documented overrides'],
    recommendation:
        'Expose semantic wrappers backed by the existing Material themes.',
  ),
  UiAuditItem(
    id: 'action-save-pill',
    category: UiAuditCategory.actions,
    kind: UiAuditKind.existing,
    decision: UiAuditDecision.keep,
    name: 'SaveActionButton',
    origins: [
      'pill_action_button.dart',
      'star_form_screen.dart',
      'constellation_editor_screen.dart',
    ],
    states: ['lit', 'unlit but explainable', 'pressed'],
    differences: 'A glowing primary pill with the same height and padding grammar as adjacent actions.',
    rationale: 'It represents the final act of lighting/saving through color and glow, not through extra width.',
    risks: 'A fixed or forced width would create empty space and make button geometry depend on location rather than content.',
    options: ['Intrinsic content width', 'Forced shared width'],
    recommendation: 'Keep as the primary commit action with intrinsic content width and centered icon/label; importance comes from fill and glow, not size.',
  ),
  UiAuditItem(
    id: 'action-pill-utility-danger',
    category: UiAuditCategory.actions,
    kind: UiAuditKind.existing,
    decision: UiAuditDecision.keep,
    name: 'PillActionButton',
    origins: [
      'pill_action_button.dart',
      'star_form_screen.dart',
      'constellation_editor_screen.dart',
    ],
    states: ['normal', 'danger', 'disabled', 'pressed'],
    differences: 'Compact icon-and-label pill used for undo, redo and delete.',
    rationale: 'Secondary canvas/form actions need less emphasis than save.',
    risks: 'Danger styling is not yet used consistently by every delete/cancel action elsewhere.',
    options: ['Keep', 'Merge into Material buttons'],
    recommendation: 'Keep as an intrinsic-width utility/destructive action with centered icon and label.',
  ),
  UiAuditItem(
    id: 'action-cancel-meanings',
    category: UiAuditCategory.actions,
    kind: UiAuditKind.existing,
    decision: UiAuditDecision.replace,
    name: 'Cancel, close and discard actions',
    origins: [
      'star_form_screen.dart',
      'constellation_editor_screen.dart',
      'vision_editor_screen.dart',
      'new_project_screen.dart',
    ],
    states: ['neutral exit', 'discard changes', 'destructive confirmation'],
    differences: 'The words cancel, close and discard are rendered as muted text, gold text, danger text, icons or pills depending on location.',
    rationale: 'The actions have genuinely different consequences but currently lack semantic types.',
    risks: 'A harmless cancel may look destructive, or a destructive discard may look harmless.',
    options: [
      'One cancel style',
      'Separate cancel, close and destructive discard',
    ],
    recommendation: 'Separate neutral cancel/close from destructive discard; base style on consequence, not label.',
  ),
  UiAuditItem(
    id: 'action-semantic-candidate',
    category: UiAuditCategory.actions,
    kind: UiAuditKind.candidate,
    decision: UiAuditDecision.review,
    name: 'Candidate semantic actions',
    origins: ['app_theme.dart', 'pill_action_button.dart'],
    states: ['enabled', 'pressed', 'focused', 'disabled', 'loading'],
    differences:
        'Four roles: primary commit, secondary, quiet and destructive.',
    rationale:
        'Call sites should choose intent rather than reconstruct appearance.',
    risks: 'Loading and explainable-disabled behavior need explicit policy before migration.',
    options: ['Four roles', 'Four roles plus compact variants'],
    recommendation: 'Use four roles with shared height and padding tokens. Every text button keeps intrinsic content width and centers its icon/label; compact density is reserved for icon-only toolbars.',
  ),
  UiAuditItem(
    id: 'field-shared',
    category: UiAuditCategory.fields,
    kind: UiAuditKind.existing,
    decision: UiAuditDecision.keep,
    name: 'AppTextField and AppPickerField',
    origins: [
      'app_field.dart',
      'star_form_screen.dart',
      'new_project_screen.dart',
    ],
    states: ['empty', 'filled', 'focused'],
    differences: 'Shared typed and picker fields follow the same dark → gold → glow state language.',
    rationale:
        'The implementation already encodes the intended gold theme behavior.',
    risks: 'Error, disabled and read-only states are not part of the shared state model.',
    options: ['Keep three states', 'Add error, disabled and read-only'],
    recommendation:
        'Keep and extend the semantic state model before wider adoption.',
  ),
  UiAuditItem(
    id: 'field-raw-text-fields',
    category: UiAuditCategory.fields,
    kind: UiAuditKind.existing,
    decision: UiAuditDecision.replace,
    name: 'Raw TextField variants',
    origins: [
      'moodboard_screen.dart',
      'constellation_editor_screen.dart',
      'vision_editor_screen.dart',
    ],
    states: ['empty', 'filled', 'focused', 'validation'],
    differences: 'Several dialog and editor fields rely on InputDecorationTheme or local decoration instead of AppTextField.',
    rationale: 'Some need controller lifetime or multiline behavior not originally exposed by the shared widget.',
    risks: 'Filled and focused states no longer match picker fields; validation presentation differs.',
    options: ['Extend AppTextField', 'Keep dialog-specific exception'],
    recommendation: 'Extend the shared field where feasible; document any dialog exception.',
  ),
  UiAuditItem(
    id: 'selection-toggle-chip',
    category: UiAuditCategory.selection,
    kind: UiAuditKind.existing,
    decision: UiAuditDecision.keep,
    name: 'AppToggleChip',
    origins: ['app_toggle_chip.dart', 'admire_stars_screen.dart'],
    states: ['off', 'on', 'pressed'],
    differences: 'A shared labelled switch pill using the global switch theme and selectable surface rule.',
    rationale: 'It replaced multiple hand-built toggles.',
    risks: 'No disabled state; compact transform can reduce the apparent control size.',
    options: ['Keep', 'Use plain SwitchListTile'],
    recommendation: 'Keep and add a disabled contract plus semantics test.',
  ),
  UiAuditItem(
    id: 'selection-local-chips',
    category: UiAuditCategory.selection,
    kind: UiAuditKind.existing,
    decision: UiAuditDecision.replace,
    name: 'Local filter and frequency chips',
    origins: [
      'area_filter_sheet.dart',
      'kind_filter_sheet.dart',
      'date_range_filter_sheet.dart',
      'star_form_screen.dart',
    ],
    states: ['selected', 'unselected', 'disabled'],
    differences: 'Similar selectable pills vary in padding, weight, icon use and selection emphasis.',
    rationale: 'They were built around different content models.',
    risks: 'Selection is not equally visible and touch targets vary.',
    options: ['One selectable chip', 'Text and icon variants'],
    recommendation: 'Define one selectable-chip state rule with content variants, not visual variants.',
  ),
  UiAuditItem(
    id: 'surface-panel-card',
    category: UiAuditCategory.surfaces,
    kind: UiAuditKind.existing,
    decision: UiAuditDecision.keep,
    name: 'Panel and selectable decorations',
    origins: ['app_style.dart', 'app_field.dart', 'kind_filter_sheet.dart'],
    states: ['neutral', 'selected'],
    differences: 'Shared radius and border rules already distinguish containers from selectable surfaces.',
    rationale: 'The supernova grammar is explicit and accessible without relying only on glow.',
    risks: 'Many cards still hand-roll equivalent BoxDecorations.',
    options: ['Keep functions', 'Promote to widgets/theme extension'],
    recommendation: 'Keep the rules and expose semantic surface widgets when migration begins.',
  ),
  UiAuditItem(
    id: 'surface-card-families',
    category: UiAuditCategory.surfaces,
    kind: UiAuditKind.existing,
    decision: UiAuditDecision.review,
    name: 'Domain card families',
    origins: [
      'lit_star_card.dart',
      'dead_star_card.dart',
      'pulsar_card.dart',
      'search_result_card.dart',
    ],
    states: ['resting', 'pressed', 'expanded/menu open'],
    differences: 'Cards intentionally represent different star types, while padding, metadata hierarchy and menus also drift within equivalent contexts.',
    rationale: 'Domain identity should remain expressive.',
    risks: 'Structural inconsistency can be confused with meaningful domain styling.',
    options: ['Keep all', 'Shared card shell with domain content'],
    recommendation: 'Keep domain visuals but converge shell spacing, hit behavior and metadata roles.',
  ),
  UiAuditItem(
    id: 'overlay-alert-dialogs',
    category: UiAuditCategory.overlays,
    kind: UiAuditKind.existing,
    decision: UiAuditDecision.replace,
    name: 'AlertDialog variants',
    origins: [
      'settings_screen.dart',
      'star_form_screen.dart',
      'new_project_screen.dart',
      'sky_explorer_view.dart',
    ],
    states: ['information', 'confirmation', 'destructive', 'blocking'],
    differences: 'The global dialog surface is shared, but title animation, padding, icon, button order and action colors vary.',
    rationale: 'Dialogs serve different purposes but are assembled ad hoc.',
    risks: 'Destructive hierarchy and dismissal behavior are inconsistent.',
    options: ['One dialog template', 'Purpose-specific dialog templates'],
    recommendation: 'Define information, confirmation, destructive and choice templates on one shell.',
  ),
  UiAuditItem(
    id: 'overlay-custom-dialogs',
    category: UiAuditCategory.overlays,
    kind: UiAuditKind.existing,
    decision: UiAuditDecision.review,
    name: 'Custom Dialog surfaces',
    origins: [
      'creation_success_dialog.dart',
      'star_form_screen.dart',
      'sky_menu_drawer.dart',
    ],
    states: ['success', 'media choice', 'menu choice'],
    differences: 'Custom layouts use different constraints, action arrangements and decoration while sharing the modal route.',
    rationale: 'These experiences do not fit AlertDialog content well.',
    risks:
        'Width, safe area and keyboard handling vary on web and narrow phones.',
    options: ['Keep exceptions', 'Shared modal shell with named layouts'],
    recommendation:
        'Use one responsive modal shell and retain purpose-specific bodies.',
  ),
  UiAuditItem(
    id: 'overlay-bottom-sheets',
    category: UiAuditCategory.overlays,
    kind: UiAuditKind.existing,
    decision: UiAuditDecision.replace,
    name: 'Bottom sheet families',
    origins: [
      'area_filter_sheet.dart',
      'date_range_filter_sheet.dart',
      'sort_filter_sheet.dart',
      'project_picker.dart',
    ],
    states: ['compact', 'scrolling', 'keyboard open', 'wide viewport'],
    differences: 'Headers, handles, heights, section labels and confirmation controls are independently implemented.',
    rationale: 'Content density differs, but chrome should not.',
    risks: 'Keyboard and safe-area behavior can break; the same filter flow feels different.',
    options: ['One rigid sheet', 'Shared shell with flexible body'],
    recommendation: 'Adopt a shared responsive sheet shell with optional search and footer slots.',
  ),
  UiAuditItem(
    id: 'navigation-icon-buttons',
    category: UiAuditCategory.navigation,
    kind: UiAuditKind.existing,
    decision: UiAuditDecision.review,
    name: 'Back, close and directional controls',
    origins: [
      'star_reader_screen.dart',
      'area_image_screen.dart',
      'constellation_editor_screen.dart',
    ],
    states: ['enabled', 'pressed', 'disabled'],
    differences: 'Circular, transparent and styled IconButtons use different sizes and backgrounds for equivalent navigation actions.',
    rationale: 'Overlay navigation needs contrast while page navigation often does not.',
    risks: 'Touch targets and affordance differ; close and back may be visually interchangeable.',
    options: ['One control', 'Page and overlay navigation roles'],
    recommendation: 'Define page-navigation and overlay-navigation roles with a 48 dp minimum target.',
  ),
  UiAuditItem(
    id: 'navigation-sky-controls',
    category: UiAuditCategory.navigation,
    kind: UiAuditKind.existing,
    decision: UiAuditDecision.exception,
    name: 'Sky overlay controls',
    origins: ['sky_screen.dart', 'app_style.dart'],
    states: ['resting', 'pressed', 'menu expanded', 'tutorial highlighted'],
    differences: 'Translucent sky controls and the white-on-navy quick menu deliberately differ from page controls.',
    rationale: 'They float directly over an animated sky and need a distinct layer language.',
    risks: 'Exceptions can leak into ordinary pages if not documented.',
    options: ['Keep exception', 'Force page style'],
    recommendation: 'Keep as a documented environment-specific family.',
  ),
  UiAuditItem(
    id: 'feedback-errors',
    category: UiAuditCategory.feedback,
    kind: UiAuditKind.existing,
    decision: UiAuditDecision.review,
    name: 'Validation and error feedback',
    origins: ['app_lock_screen.dart', 'star_form_screen.dart', 'main.dart'],
    states: ['inline error', 'blocking explanation', 'load failure'],
    differences: 'Errors appear as small inline danger text, modal explanations or raw bootstrap text.',
    rationale: 'Severity and recovery differ.',
    risks: 'Some errors lack an associated field or recovery action; screen-reader announcement is uncertain.',
    options: ['One pattern', 'Inline, banner and blocking roles'],
    recommendation: 'Define feedback by severity and recovery path, including live-region semantics.',
  ),
  UiAuditItem(
    id: 'feedback-loading',
    category: UiAuditCategory.feedback,
    kind: UiAuditKind.existing,
    decision: UiAuditDecision.review,
    name: 'Loading and progress states',
    origins: ['main.dart', 'settings_screen.dart', 'star_reader_screen.dart'],
    states: ['initial load', 'button work', 'content refresh'],
    differences: 'Some flows disable controls, some show progress indicators, and startup intentionally stays blank.',
    rationale:
        'Different durations and interruption costs need different feedback.',
    risks: 'A blank or disabled interface can look frozen.',
    options: [
      'Spinner everywhere',
      'Named initial, inline and action-loading patterns',
    ],
    recommendation:
        'Define three loading patterns and minimum feedback timing.',
  ),
  UiAuditItem(
    id: 'spacing-page-insets',
    category: UiAuditCategory.spacing,
    kind: UiAuditKind.existing,
    decision: UiAuditDecision.replace,
    name: 'Page and modal insets',
    origins: [
      'area_detail_screen.dart',
      'admire_stars_screen.dart',
      'quick_settings_screen.dart',
      'creation_success_dialog.dart',
    ],
    states: ['narrow phone', 'phone', 'wide web'],
    differences: 'Primary horizontal insets commonly use 20, 24 or 28 dp; modal padding also changes between implementations.',
    rationale: 'Immersive screens sometimes need more breathing room.',
    risks: 'Alignment shifts between routes and usable width becomes unpredictable.',
    options: ['Single inset', 'Compact/regular/immersive tokens'],
    recommendation:
        'Adopt compact, regular and immersive inset tokens tied to context.',
  ),
  UiAuditItem(
    id: 'spacing-radius-scale',
    category: UiAuditCategory.spacing,
    kind: UiAuditKind.existing,
    decision: UiAuditDecision.keep,
    name: 'Radius scale',
    origins: [
      'app_style.dart',
      'moodboard_grid.dart',
      'looping_hero_carousel.dart',
    ],
    states: ['field', 'card', 'pill', 'artwork'],
    differences: 'Most interactive surfaces use 12, containers use 16 and actions use stadiums; a small number of local 14/28 values remain.',
    rationale: 'Artwork and media crops can justify distinct geometry.',
    risks: 'Unlabelled local values become accidental fourth and fifth design-system steps.',
    options: ['Strict three-step scale', 'Allow documented media radius'],
    recommendation:
        'Keep the three-step UI scale and name any media-only exception.',
  ),
  UiAuditItem(
    id: 'color-gold-state-language',
    category: UiAuditCategory.color,
    kind: UiAuditKind.existing,
    decision: UiAuditDecision.keep,
    name: 'Gold state language',
    origins: ['app_colors.dart', 'app_style.dart', 'app_theme.dart'],
    states: ['inactive', 'selected', 'focused', 'primary'],
    differences: 'Navy and flat means available/inactive; gold ring means selected/filled; gold fill or glow means active primary energy.',
    rationale:
        'This is the clearest existing design principle in the codebase.',
    risks: 'Some local widgets use gold merely as decoration, weakening the state signal.',
    options: ['Keep semantic gold', 'Use gold decoratively everywhere'],
    recommendation: 'Reserve gold intensity for state and importance; audit decorative exceptions.',
  ),
  UiAuditItem(
    id: 'color-raw-values',
    category: UiAuditCategory.color,
    kind: UiAuditKind.existing,
    decision: UiAuditDecision.replace,
    name: 'Raw Color and Colors values',
    origins: [
      'moodboard_grid.dart',
      'sky_screen.dart',
      'nightlight screens',
      'shareable cards',
    ],
    states: ['content', 'overlay', 'export asset'],
    differences: 'Raw white, transparent and fixed ARGB values occur alongside palette colors.',
    rationale: 'Shaders, exports and nightlight artwork sometimes require fixed colors.',
    risks: 'Ordinary controls can bypass palette semantics and contrast rules.',
    options: [
      'Ban raw colors',
      'Allow only documented rendering/export exceptions',
    ],
    recommendation: 'Use the standard night/gold palette throughout the app. The white-on-black meta theme is reserved for Manage Areas and Nightlight; fixed colors remain allowed only inside artwork and shaders.',
  ),
  UiAuditItem(
    id: 'icons-size-and-container',
    category: UiAuditCategory.icons,
    kind: UiAuditKind.existing,
    decision: UiAuditDecision.review,
    name: 'Icon sizes and containers',
    origins: [
      'sky_screen.dart',
      'star_reader_screen.dart',
      'sound_lab_screen.dart',
    ],
    states: ['standalone', 'inside button', 'decorative'],
    differences: 'Icons use many optical sizes and may be bare, circled, gold-ringed or placed in pills.',
    rationale:
        'Optical correction is legitimate, especially for custom SVG assets.',
    risks: 'Visual size and touch target are often conflated.',
    options: ['One icon size', 'Named glyph sizes independent of hit targets'],
    recommendation: 'Define glyph size tokens and enforce separate 48 dp interaction targets.',
  ),
  UiAuditItem(
    id: 'motion-entrances',
    category: UiAuditCategory.motion,
    kind: UiAuditKind.existing,
    decision: UiAuditDecision.review,
    name: 'Entrance and emphasis motion',
    origins: ['staggered_entrance.dart', 'app_motion.dart', 'sky_screen.dart'],
    states: ['route enter', 'dialog enter', 'pressed', 'reduced motion'],
    differences: 'Shared staggered entrances coexist with bespoke sky, carousel and button animations.',
    rationale: 'The sky is an immersive environment and needs richer motion.',
    risks: 'Dialogs apply animation inconsistently; reduced-motion behavior must remain predictable.',
    options: ['Uniform motion', 'Core motion plus immersive exceptions'],
    recommendation: 'Keep an accessible core motion scale and document immersive exceptions.',
  ),
  UiAuditItem(
    id: 'modal-shell-candidate',
    category: UiAuditCategory.overlays,
    kind: UiAuditKind.candidate,
    decision: UiAuditDecision.review,
    name: 'Candidate responsive modal shell',
    origins: ['app_modals.dart', 'app_theme.dart'],
    states: ['dialog', 'sheet', 'keyboard visible', 'wide viewport'],
    differences: 'One shell would own width, padding, safe area, dismiss behavior and action layout.',
    rationale: 'Purpose-specific content can remain different without rebuilding modal chrome.',
    risks: 'A rigid shell could harm media pickers or immersive menu content.',
    options: ['Single shell', 'Dialog and sheet shells sharing tokens'],
    recommendation:
        'Use separate dialog and sheet shells backed by the same modal tokens.',
  ),
  UiAuditItem(
    id: 'surface-semantic-candidate',
    category: UiAuditCategory.surfaces,
    kind: UiAuditKind.candidate,
    decision: UiAuditDecision.review,
    name: 'Candidate semantic surfaces',
    origins: ['app_style.dart'],
    states: ['neutral', 'selectable', 'selected', 'disabled', 'focused'],
    differences:
        'Named shells would turn decoration functions into explicit UI roles.',
    rationale: 'Call sites currently mix layout and state styling.',
    risks: 'Too many wrappers could make highly custom cards harder to build.',
    options: ['Decoration helpers only', 'Small semantic surface widget'],
    recommendation:
        'Add a small surface primitive later; keep domain cards composable.',
  ),
];
