import 'dart:io';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:inner_stars/widgets/badge_icon.dart';
import 'package:inner_stars/widgets/badge_icon_ink.dart';

/// Measures the painted part of every badge icon from the Material Icons
/// font and checks it against `lib/widgets/badge_icon_ink.dart`. Pass
/// `--dart-define=WRITE_BADGE_ICON_INK=true` to rewrite that file.
void main() {
  const write = bool.fromEnvironment('WRITE_BADGE_ICON_INK');
  const side = 480;

  File? fontFile() {
    final root = Platform.environment['FLUTTER_ROOT'];
    final candidates = [
      if (root != null)
        '$root/bin/cache/artifacts/material_fonts/materialicons-regular.otf',
      'C:/flutter/flutter/bin/cache/artifacts/material_fonts/materialicons-regular.otf',
    ];
    for (final path in candidates) {
      final file = File(path);
      if (file.existsSync()) return file;
    }
    return null;
  }

  Future<BadgeIconInk> measure(IconData icon) async {
    final recorder = ui.PictureRecorder();
    final canvas = Canvas(recorder);
    final painter = TextPainter(
      textDirection: TextDirection.ltr,
      text: TextSpan(
        text: String.fromCharCode(icon.codePoint),
        style: TextStyle(
          fontFamily: icon.fontFamily,
          fontSize: side.toDouble(),
          height: 1,
          leadingDistribution: TextLeadingDistribution.even,
          color: Colors.white,
        ),
      ),
    )..layout();
    // The glyph's em square starts at the painter's top-left; paint it there
    // and measure relative to that corner.
    painter.paint(canvas, Offset.zero);
    final image = await recorder.endRecording().toImage(
      painter.width.ceil() + 8,
      painter.height.ceil() + 8,
    );
    final bytes = (await image.toByteData(format: ui.ImageByteFormat.rawRgba))!
        .buffer
        .asUint8List();
    final w = image.width;
    final h = image.height;
    var minX = w, minY = h, maxX = -1, maxY = -1;
    var massSum = 0.0, massY = 0.0;
    for (var y = 0; y < h; y++) {
      for (var x = 0; x < w; x++) {
        final alpha = bytes[(y * w + x) * 4 + 3];
        massSum += alpha;
        massY += alpha * (y + 0.5);
        if (alpha > 24) {
          if (x < minX) minX = x;
          if (x > maxX) maxX = x;
          if (y < minY) minY = y;
          if (y > maxY) maxY = y;
        }
      }
    }
    double r(num v) => (v / side * 10000).round() / 10000;
    return BadgeIconInk(
      r(minX),
      r(minY),
      r(maxX + 1),
      r(maxY + 1),
      r(massY / massSum),
    );
  }

  testWidgets('badge icon ink matches the font', (tester) async {
    final file = fontFile();
    if (file == null) {
      markTestSkipped('Material Icons font not found');
      return;
    }
    final loader = FontLoader('MaterialIcons')
      ..addFont(Future.value(ByteData.sublistView(file.readAsBytesSync())));
    await loader.load();
    final measured = <int, BadgeIconInk>{};
    await tester.runAsync(() async {
      for (final icon in kBadgeIconSet) {
        measured[icon.codePoint] = await measure(icon);
      }
    });

    if (write) {
      final out = StringBuffer()
        ..writeln(
          '// GENERATED by test/widgets/badge_icon_ink_test.dart — do not edit '
          'by hand.',
        )
        ..writeln(
          '// Run: flutter test test/widgets/badge_icon_ink_test.dart '
          '--dart-define=WRITE_BADGE_ICON_INK=true',
        )
        ..writeln('const Map<int, BadgeIconInk> kBadgeIconInk = {');
      for (final icon in kBadgeIconSet) {
        final m = measured[icon.codePoint]!;
        out.writeln(
          '  0x${icon.codePoint.toRadixString(16)}: '
          'BadgeIconInk(${m.left}, ${m.top}, ${m.right}, ${m.bottom}, ${m.massY}),',
        );
      }
      out
        ..writeln('};')
        ..writeln()
        ..writeln(
          '/// The painted part of a Material icon: its left, top, right and '
          'bottom edge',
        )
        ..writeln("/// as a fraction of the icon's em square.")
        ..writeln('class BadgeIconInk {')
        ..writeln('  const BadgeIconInk(')
        ..writeln('    this.left,')
        ..writeln('    this.top,')
        ..writeln('    this.right,')
        ..writeln('    this.bottom,')
        ..writeln('    this.massY,')
        ..writeln('  );')
        ..writeln()
        ..writeln('  final double left;')
        ..writeln('  final double top;')
        ..writeln('  final double right;')
        ..writeln('  final double bottom;')
        ..writeln()
        ..writeln(
          "  /// Where the drawing's weight is, top to bottom (its centre of mass).",
        )
        ..writeln('  final double massY;')
        ..writeln()
        ..writeln('  double get width => right - left;')
        ..writeln('  double get height => bottom - top;')
        ..writeln('}');
      File('lib/widgets/badge_icon_ink.dart').writeAsStringSync(out.toString());
      return;
    }

    for (final icon in kBadgeIconSet) {
      final expected = kBadgeIconInk[icon.codePoint];
      final m = measured[icon.codePoint]!;
      expect(expected, isNotNull, reason: 'no ink for ${icon.codePoint}');
      expect(expected!.left, closeTo(m.left, 0.005));
      expect(expected.top, closeTo(m.top, 0.005));
      expect(expected.right, closeTo(m.right, 0.005));
      expect(expected.bottom, closeTo(m.bottom, 0.005));
      expect(expected.massY, closeTo(m.massY, 0.005));
    }
  });
}
