// GENERATED by test/widgets/badge_icon_ink_test.dart — do not edit by hand.
// Run: flutter test test/widgets/badge_icon_ink_test.dart --dart-define=WRITE_BADGE_ICON_INK=true
const Map<int, BadgeIconInk> kBadgeIconInk = {
  0xf5ca: BadgeIconInk(0.2917, 0.125, 0.7104, 0.875, 0.4998),
  0xf06c8: BadgeIconInk(0.125, 0.0833, 0.875, 0.9167, 0.4777),
  0xf696: BadgeIconInk(0.2083, 0.125, 0.7917, 0.875, 0.4757),
  0xe30e: BadgeIconInk(0.0583, 0.0833, 0.9167, 0.9417, 0.5102),
  0xf01d4: BadgeIconInk(0.1438, 0.1479, 0.8563, 0.8313, 0.5203),
  0xf01d1: BadgeIconInk(0.1438, 0.1479, 0.8563, 0.8313, 0.5201),
  0xef53: BadgeIconInk(0.0833, 0.0833, 0.9167, 0.9167, 0.4997),
  0xf86b: BadgeIconInk(0.1646, 0.1146, 0.8333, 0.8354, 0.4938),
  0xf02f: BadgeIconInk(0.125, 0.0833, 0.875, 0.9167, 0.512),
  0xf29d: BadgeIconInk(0.0833, 0.0833, 0.9167, 0.9167, 0.5281),
  0xf132: BadgeIconInk(0.0396, 0.125, 0.9604, 0.8354, 0.5233),
  0xeeaf: BadgeIconInk(0.0396, 0.0208, 0.9604, 0.8333, 0.4738),
  0xf00d: BadgeIconInk(0.125, 0.125, 0.875, 0.875, 0.5162),
  0xf8bb: BadgeIconInk(0.2104, 0.0833, 0.7896, 0.875, 0.4782),
  0xf48c: BadgeIconInk(0.125, 0.25, 0.875, 0.75, 0.5),
  0xf85a: BadgeIconInk(0.0833, 0.2896, 0.9167, 0.7104, 0.5001),
  0xe1b6: BadgeIconInk(0.125, 0.0833, 0.875, 0.9167, 0.4686),
  0xe338: BadgeIconInk(0.2083, 0.125, 0.7917, 0.875, 0.5),
};

/// The painted part of a Material icon: its left, top, right and bottom edge
/// as a fraction of the icon's em square.
class BadgeIconInk {
  const BadgeIconInk(this.left, this.top, this.right, this.bottom, this.massY);

  final double left;
  final double top;
  final double right;
  final double bottom;

  /// Where the drawing's weight is, top to bottom (its centre of mass).
  final double massY;

  double get width => right - left;
  double get height => bottom - top;
}
